### ISSUE TITLE
问一下`puppet.agent.downloadFile`的使用

### ISSUE THREAD

**Issue by zjy1412** [wechatferry/wechatferry#14]
```
  async tryDownloadFile(msg, targetPath) {
    // 直接使用 puppet.agent.downloadFile
    try {
      log('info', `尝试使用 puppet.agent.downloadFile 下载文件`);
      if (!this.puppet?.agent) {
        throw new Error('Puppet agent not available');
      }

      const fileBox = await this.puppet.agent.downloadFile(msg);
      if (!fileBox) {
        throw new Error('No file downloaded');
      }

      await fileBox.toFile(targetPath);
      return { success: true, method: 'agent.downloadFile' };
    } catch (error) {
      log('warn', `文件下载失败: ${error.message}`);
      // 如果下载失败但至少有文件信息，标记为元数据模式
      if (msg.payload?.text?.includes('<appmsg>')) {
        return { success: true, method: 'metadata_only' };
      }
      return { success: false, error: error.message };
    }
  }
  ```
  
  目前的代码是这样的，但是所有格式的文件都下载失败，报错是
  ```
  unsupported message type
  ```
  
  是使用方式有问题吗？

**Comment by KeJunMao** [comment]
直接 `msg.toFileBox()`

**Comment by zjy1412** [comment]
@KeJunMao 我用`msg.toFileBox()`好像只能下载图片？下载pdf这些都失败了。

**Comment by zjy1412** [comment]
> > @KeJunMao 我用`msg.toFileBox()`好像只能下载图片？下载pdf这些都失败了。
> 
> ```
> 使用 FileBox 方式下载文件...
> Message type: 1
> FileBox 下载失败: Error: downloadFile([object Object]): unsupported message type
>     at WechatferryAgent.downloadFile (file:///D:/projects/wechatyferry-bot/wechatyferry-bot/node_modules/@wechatferry/agent/dist/index.mjs:336:11)
>     at WechatferryPuppet.messageFile (file:///D:/projects/wechatyferry-bot/wechatyferry-bot/node_modules/@wechatferry/puppet/dist/index.mjs:1416:27)
>     at async WechatifiedUserClass.toFileBox (file:///D:/projects/wechatyferry-bot/wechatyferry-bot/node_modules/wechaty/dist/esm/src/user-modules/message.js:806:25)
>     at async downloadUsingFileBox (file:///D:/projects/wechatyferry-bot/wechatyferry-bot/test.js:43:22)
>     at async WechatyImpl.<anonymous> (file:///D:/projects/wechatyferry-bot/wechatyferry-bot/test.js:76:21)
> ```
> 
> 用`msg.toFileBox()`准备下txt文件的时候，他好像也又转到`WechatferryAgent.downloadFile `去了

看了一下源码的实现：
```
  async messageFile(messageId) {
    const rawMessage = await this.messageRawPayload(messageId);
    const message = await this.messageRawPayloadParser(rawMessage);
    switch (message.type) {
      case PUPPET.types.Message.Image:
        return this.messageImage(messageId, PUPPET.types.Image.HD);
      case PUPPET.types.Message.Video:
      case PUPPET.types.Message.Attachment:
      case PUPPET.types.Message.Audio:
        return this.agent.downloadFile(rawMessage);
      case PUPPET.types.Message.Emoticon: {
        const emotionPayload = await parseEmotionMessagePayload(message);
        const emoticonBox = FileBox.fromUrl(emotionPayload.cdnurl, { name: `message-${messageId}-emoticon.jpg` });
        emoticonBox.metadata = {
          payload: emotionPayload,
          type: "emoticon"
        };
        return emoticonBox;
      }
    }
```

这么实现是因为wechaty本来就只能下载图片？

**Comment by zjy1412** [comment]
我怀疑这个问题始终存在？因为我看到wechaty的这个[issue](https://github.com/wechaty/wechaty/issues/2596)。

**Comment by KeJunMao** [comment]
你可以尝试直接用 core 下载文件吗

**Comment by zjy1412** [comment]
> 你可以尝试直接用 core 下载文件吗

`bot.puppet.agent.wcf.downloadAttach`，使用这个？`thumb`和`extra`对应消息中的？

```
    /**
     * 下载附件（图片、视频、文件
     * @param id 消息中 id
     * @param thumb 消息中的 thumb
     * @param extra 消息中的 extra
     * @returns 0 为成功, 其他失败。
     */
    downloadAttach(id: string, thumb?: string, extra?: string): number;
```

**Comment by KeJunMao** [comment]
是的，对应原始 tcp 解析后的消息中的字段

如果是历史消息，似乎可以从数据库中查出来，但是我忘了有没有实现解析...

**Comment by zjy1412** [comment]
> 是的，对应原始 tcp 解析后的消息中的字段
> 
> 如果是历史消息，似乎可以从数据库中查出来，但是我忘了有没有实现解析...

这个extra应该是下面的哪个？`fileuploadtoken`？试了也不是呀。

```
完整消息对象: WechatifiedMessageImpl {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  id: '3121596210077946571',
  payload: {
    id: '3121596210077946571',
    text: '<msg>\n' +
      '    <fromusername>wxid_vmgsiu9kbogc31</fromusername>\n' +
      '    <scene>0</scene>\n' +
      '    <commenturl></commenturl>\n' +
      '    <appmsg appid="" sdkver="0">\n' +
      '        <title>1.pdf</title>\n' +
      '        <des></des>\n' +
      '        <action>view</action>\n' +
      '        <type>6</type>\n' +
      '        <showtype>0</showtype>\n' +
      '        <content></content>\n' +
      '        <url></url>\n' +
      '        <dataurl></dataurl>\n' +
      '        <lowurl></lowurl>\n' +
      '        <lowdataurl></lowdataurl>\n' +
      '        <recorditem></recorditem>\n' +
      '        <thumburl></thumburl>\n' +
      '        <messageaction></messageaction>\n' +
      '        <laninfo></laninfo>\n' +
      '        <md5>3bede6302f4f44aab0854031a867721d</md5>\n' +
      '        <extinfo></extinfo>\n' +
      '        <sourceusername></sourceusername>\n' +
      '        <sourcedisplayname></sourcedisplayname>\n' +
      '        <commenturl></commenturl>\n' +
      '        <appattach>\n' +
      '            <totallen>略</totallen>\n' +
      '            <attachid></attachid>\n' +
      '            <emoticonmd5></emoticonmd5>\n' +
      '            <fileext>pdf</fileext>\n' +
      '            <fileuploadtoken>v1_TGzlAeTsV6kJ5/3YQhGRiB+I8/25qfo7q5Kh7qqkDntBNZj9Jv/IcIDT1XXH0oUtf82BZA/U4kOG74JLZu2kjX1zsLd9fmtuIDZrng8J6wSG3VbNzJS5DChv4TyshGnRHujToSJ5DBsxw2Ht6+291FXXgpZPnAJK8jazSiQWh79BLwBcCbwqJkZz1HXRZ4t0CqQqz+31ctsD/NGR286iNPUScQ9lOvPJ5n69fg078OmrlZjwthc6Wlx5y5mDQNExcvYI9tbCWSN7aNkboqYi52/wUmpV/DBA6iCn7Xx1a8OG/rnfqNpl6btoAHUBZ1zYB6cTP6fAb0rLQ/r</fileuploadtoken>\n' +    
      '            <aeskey></aeskey>\n' +
      '        </appattach>\n' +
      '        <webviewshared>\n' +
      '            <publisherId></publisherId>\n' +
      '            <publisherReqId>0</publisherReqId>\n' +
      '        </webviewshared>\n' +
      '        <weappinfo>\n' +
      '            <pagepath></pagepath>\n' +
      '            <username></username>\n' +
      '            <appid></appid>\n' +
      '            <appservicetype>0</appservicetype>\n' +
      '        </weappinfo>\n' +
      '        <websearch />\n' +
      '    </appmsg>\n' +
      '    <appinfo>\n' +
      '        <version>1</version>\n' +
      '        <appname>Window wechat</appname>\n' +
      '    </appinfo>\n' +
      '</msg>\n',
    talkerId: 略,
    listenerId: 略,
    timestamp: 1731661000065,
    roomId: '',
    isRefer: false,
    type: 1,
    filename: '1.pdf'
  },
  [Symbol(kCapture)]: false
}
```

**Comment by KeJunMao** [comment]
这个不是 原始消息嗷，需要 rawMessage 里拿

**Comment by mrchengxin** [comment]
我是这样临时解决的，以备其他人需要：
```typescript
  private puppet: WechatferryPuppet;
  ...

  async handleAttachmentMessage(
    message: MessageInterface,
    timeout: number = 30,
  ) {
    // 从message拿到raw message
    const rawMessage = await this.puppet.messageRawPayload(message.id);

    // wechatferry通知微信开始下载文件
    const { id, thumb, extra } = rawMessage;
    const status = this.puppet.agent.wcf.downloadAttach(id, thumb, extra);
    if (status !== 0) {
      this.logger.error(`error downloading attachment`);
      return;
    }

    // 等待文件下载完成后，转成FileBox返回
    const wechatFilePath = thumb.endsWith('.mp4') ? thumb : extra;
    for (let cnt = 0; cnt < timeout; cnt++) {
      if (fs.existsSync(wechatFilePath)) {
        return FileBox.fromFile(wechatFilePath);
      }
      await setTimeout(1000);
    }
    this.logger.error(`download file timeout`);
  }
```

**Comment by specialYmx** [comment]
目前使用的wechatferry0.0.24+wechaty2.10，请问下现在还是获取不了文件类型的数据吗比如doc，pdf，excel这些文件，调用那个toFIleBox()方法仍然会报这个错误，
我之前使用的wechaty0.xx版本+padlocal协议 是可以正常获取文件的数据的

**Comment by specialYmx** [comment]
> 我是这样临时解决的，以备其他人需要：
> 
>   private puppet: WechatferryPuppet;
>   ...
> 
>   async handleAttachmentMessage(
>     message: MessageInterface,
>     timeout: number = 30,
>   ) {
>     // 从message拿到raw message
>     const rawMessage = await this.puppet.messageRawPayload(message.id);
> 
>     // wechatferry通知微信开始下载文件
>     const { id, thumb, extra } = rawMessage;
>     const status = this.puppet.agent.wcf.downloadAttach(id, thumb, extra);
>     if (status !== 0) {
>       this.logger.error(`error downloading attachment`);
>       return;
>     }
> 
>     // 等待文件下载完成后，转成FileBox返回
>     const wechatFilePath = thumb.endsWith('.mp4') ? thumb : extra;
>     for (let cnt = 0; cnt < timeout; cnt++) {
>       if (fs.existsSync(wechatFilePath)) {
>         return FileBox.fromFile(wechatFilePath);
>       }
>       await setTimeout(1000);
>     }
>     this.logger.error(`download file timeout`);
>   }

这样能实现么我用的是wechatferry-puppet，我这样写报错找不到发的文件路径呢，作者您标记到这个issue是什么意思，是这个代码可以实现功能么 @KeJunMao
